/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmailRouteImport } from './routes/email'
import { Route as QueueRouteImport } from './routes/queue'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SmsRouteImport } from './routes/sms'
import { Route as ViberRouteImport } from './routes/viber'
import { Route as VoiceRouteImport } from './routes/voice'
import { Route as WhatsappRouteImport } from './routes/whatsapp'
import { Route as ApiCallEscalationLogsRouteImport } from './routes/api/call-escalation-logs'
import { Route as ApiCallPromiseLogsRouteImport } from './routes/api/call-promise-logs'
import { Route as ApiChannelCountersRouteImport } from './routes/api/channel-counters'
import { Route as ApiClientCallSummaryRouteImport } from './routes/api/client-call-summary'
import { Route as ApiClientsListRouteImport } from './routes/api/clients-list'
import { Route as ApiDailyRunLogsRouteImport } from './routes/api/daily-run-logs'
import { Route as ApiEscalationsRouteImport } from './routes/api/escalations'
import { Route as ApiGmailAttachmentRouteImport } from './routes/api/gmail-attachment'
import { Route as ApiGmailThreadDetailRouteImport } from './routes/api/gmail-thread-detail'
import { Route as ApiGmailThreadsListRouteImport } from './routes/api/gmail-threads-list'
import { Route as ApiPromiseHistoryRouteImport } from './routes/api/promise-history'
import { Route as ApiReminderQueueListRouteImport } from './routes/api/reminder-queue-list'
import { Route as ApiSmsConversationsRouteImport } from './routes/api/sms-conversations'
import { Route as ApiVapiCallAudioRouteImport } from './routes/api/vapi-call-audio'
import { Route as ApiVapiCallDetailRouteImport } from './routes/api/vapi-call-detail'
import { Route as ApiVapiCallsListRouteImport } from './routes/api/vapi-calls-list'
import { Route as ApiWhatsappConversationsRouteImport } from './routes/api/whatsapp-conversations'
import { Route as ClientsIndexRouteImport } from './routes/clients.index'
import { Route as ClientsClientIdRouteImport } from './routes/clients.$clientId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailRoute = EmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => rootRouteImport,
} as any)
const QueueRoute = QueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SmsRoute = SmsRouteImport.update({
  id: '/sms',
  path: '/sms',
  getParentRoute: () => rootRouteImport,
} as any)
const ViberRoute = ViberRouteImport.update({
  id: '/viber',
  path: '/viber',
  getParentRoute: () => rootRouteImport,
} as any)
const VoiceRoute = VoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatsappRoute = WhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCallEscalationLogsRoute = ApiCallEscalationLogsRouteImport.update({
  id: '/api/call-escalation-logs',
  path: '/api/call-escalation-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCallPromiseLogsRoute = ApiCallPromiseLogsRouteImport.update({
  id: '/api/call-promise-logs',
  path: '/api/call-promise-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChannelCountersRoute = ApiChannelCountersRouteImport.update({
  id: '/api/channel-counters',
  path: '/api/channel-counters',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiClientCallSummaryRoute = ApiClientCallSummaryRouteImport.update({
  id: '/api/client-call-summary',
  path: '/api/client-call-summary',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiClientsListRoute = ApiClientsListRouteImport.update({
  id: '/api/clients-list',
  path: '/api/clients-list',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDailyRunLogsRoute = ApiDailyRunLogsRouteImport.update({
  id: '/api/daily-run-logs',
  path: '/api/daily-run-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEscalationsRoute = ApiEscalationsRouteImport.update({
  id: '/api/escalations',
  path: '/api/escalations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGmailAttachmentRoute = ApiGmailAttachmentRouteImport.update({
  id: '/api/gmail-attachment',
  path: '/api/gmail-attachment',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGmailThreadDetailRoute = ApiGmailThreadDetailRouteImport.update({
  id: '/api/gmail-thread-detail',
  path: '/api/gmail-thread-detail',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGmailThreadsListRoute = ApiGmailThreadsListRouteImport.update({
  id: '/api/gmail-threads-list',
  path: '/api/gmail-threads-list',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPromiseHistoryRoute = ApiPromiseHistoryRouteImport.update({
  id: '/api/promise-history',
  path: '/api/promise-history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReminderQueueListRoute = ApiReminderQueueListRouteImport.update({
  id: '/api/reminder-queue-list',
  path: '/api/reminder-queue-list',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSmsConversationsRoute = ApiSmsConversationsRouteImport.update({
  id: '/api/sms-conversations',
  path: '/api/sms-conversations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVapiCallAudioRoute = ApiVapiCallAudioRouteImport.update({
  id: '/api/vapi-call-audio',
  path: '/api/vapi-call-audio',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVapiCallDetailRoute = ApiVapiCallDetailRouteImport.update({
  id: '/api/vapi-call-detail',
  path: '/api/vapi-call-detail',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVapiCallsListRoute = ApiVapiCallsListRouteImport.update({
  id: '/api/vapi-calls-list',
  path: '/api/vapi-calls-list',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWhatsappConversationsRoute =
  ApiWhatsappConversationsRouteImport.update({
    id: '/api/whatsapp-conversations',
    path: '/api/whatsapp-conversations',
    getParentRoute: () => rootRouteImport,
  } as any)
const ClientsIndexRoute = ClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsClientIdRoute = ClientsClientIdRouteImport.update({
  id: '/clients/$clientId',
  path: '/clients/$clientId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/email': typeof EmailRoute
  '/queue': typeof QueueRoute
  '/reports': typeof ReportsRoute
  '/sms': typeof SmsRoute
  '/viber': typeof ViberRoute
  '/voice': typeof VoiceRoute
  '/whatsapp': typeof WhatsappRoute
  '/api/call-escalation-logs': typeof ApiCallEscalationLogsRoute
  '/api/call-promise-logs': typeof ApiCallPromiseLogsRoute
  '/api/channel-counters': typeof ApiChannelCountersRoute
  '/api/client-call-summary': typeof ApiClientCallSummaryRoute
  '/api/clients-list': typeof ApiClientsListRoute
  '/api/daily-run-logs': typeof ApiDailyRunLogsRoute
  '/api/escalations': typeof ApiEscalationsRoute
  '/api/gmail-attachment': typeof ApiGmailAttachmentRoute
  '/api/gmail-thread-detail': typeof ApiGmailThreadDetailRoute
  '/api/gmail-threads-list': typeof ApiGmailThreadsListRoute
  '/api/promise-history': typeof ApiPromiseHistoryRoute
  '/api/reminder-queue-list': typeof ApiReminderQueueListRoute
  '/api/sms-conversations': typeof ApiSmsConversationsRoute
  '/api/vapi-call-audio': typeof ApiVapiCallAudioRoute
  '/api/vapi-call-detail': typeof ApiVapiCallDetailRoute
  '/api/vapi-calls-list': typeof ApiVapiCallsListRoute
  '/api/whatsapp-conversations': typeof ApiWhatsappConversationsRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/clients/': typeof ClientsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/email': typeof EmailRoute
  '/queue': typeof QueueRoute
  '/reports': typeof ReportsRoute
  '/sms': typeof SmsRoute
  '/viber': typeof ViberRoute
  '/voice': typeof VoiceRoute
  '/whatsapp': typeof WhatsappRoute
  '/api/call-escalation-logs': typeof ApiCallEscalationLogsRoute
  '/api/call-promise-logs': typeof ApiCallPromiseLogsRoute
  '/api/channel-counters': typeof ApiChannelCountersRoute
  '/api/client-call-summary': typeof ApiClientCallSummaryRoute
  '/api/clients-list': typeof ApiClientsListRoute
  '/api/daily-run-logs': typeof ApiDailyRunLogsRoute
  '/api/escalations': typeof ApiEscalationsRoute
  '/api/gmail-attachment': typeof ApiGmailAttachmentRoute
  '/api/gmail-thread-detail': typeof ApiGmailThreadDetailRoute
  '/api/gmail-threads-list': typeof ApiGmailThreadsListRoute
  '/api/promise-history': typeof ApiPromiseHistoryRoute
  '/api/reminder-queue-list': typeof ApiReminderQueueListRoute
  '/api/sms-conversations': typeof ApiSmsConversationsRoute
  '/api/vapi-call-audio': typeof ApiVapiCallAudioRoute
  '/api/vapi-call-detail': typeof ApiVapiCallDetailRoute
  '/api/vapi-calls-list': typeof ApiVapiCallsListRoute
  '/api/whatsapp-conversations': typeof ApiWhatsappConversationsRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/clients': typeof ClientsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/email': typeof EmailRoute
  '/queue': typeof QueueRoute
  '/reports': typeof ReportsRoute
  '/sms': typeof SmsRoute
  '/viber': typeof ViberRoute
  '/voice': typeof VoiceRoute
  '/whatsapp': typeof WhatsappRoute
  '/api/call-escalation-logs': typeof ApiCallEscalationLogsRoute
  '/api/call-promise-logs': typeof ApiCallPromiseLogsRoute
  '/api/channel-counters': typeof ApiChannelCountersRoute
  '/api/client-call-summary': typeof ApiClientCallSummaryRoute
  '/api/clients-list': typeof ApiClientsListRoute
  '/api/daily-run-logs': typeof ApiDailyRunLogsRoute
  '/api/escalations': typeof ApiEscalationsRoute
  '/api/gmail-attachment': typeof ApiGmailAttachmentRoute
  '/api/gmail-thread-detail': typeof ApiGmailThreadDetailRoute
  '/api/gmail-threads-list': typeof ApiGmailThreadsListRoute
  '/api/promise-history': typeof ApiPromiseHistoryRoute
  '/api/reminder-queue-list': typeof ApiReminderQueueListRoute
  '/api/sms-conversations': typeof ApiSmsConversationsRoute
  '/api/vapi-call-audio': typeof ApiVapiCallAudioRoute
  '/api/vapi-call-detail': typeof ApiVapiCallDetailRoute
  '/api/vapi-calls-list': typeof ApiVapiCallsListRoute
  '/api/whatsapp-conversations': typeof ApiWhatsappConversationsRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/clients/': typeof ClientsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/email'
    | '/queue'
    | '/reports'
    | '/sms'
    | '/viber'
    | '/voice'
    | '/whatsapp'
    | '/api/call-escalation-logs'
    | '/api/call-promise-logs'
    | '/api/channel-counters'
    | '/api/client-call-summary'
    | '/api/clients-list'
    | '/api/daily-run-logs'
    | '/api/escalations'
    | '/api/gmail-attachment'
    | '/api/gmail-thread-detail'
    | '/api/gmail-threads-list'
    | '/api/promise-history'
    | '/api/reminder-queue-list'
    | '/api/sms-conversations'
    | '/api/vapi-call-audio'
    | '/api/vapi-call-detail'
    | '/api/vapi-calls-list'
    | '/api/whatsapp-conversations'
    | '/clients/$clientId'
    | '/clients/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/email'
    | '/queue'
    | '/reports'
    | '/sms'
    | '/viber'
    | '/voice'
    | '/whatsapp'
    | '/api/call-escalation-logs'
    | '/api/call-promise-logs'
    | '/api/channel-counters'
    | '/api/client-call-summary'
    | '/api/clients-list'
    | '/api/daily-run-logs'
    | '/api/escalations'
    | '/api/gmail-attachment'
    | '/api/gmail-thread-detail'
    | '/api/gmail-threads-list'
    | '/api/promise-history'
    | '/api/reminder-queue-list'
    | '/api/sms-conversations'
    | '/api/vapi-call-audio'
    | '/api/vapi-call-detail'
    | '/api/vapi-calls-list'
    | '/api/whatsapp-conversations'
    | '/clients/$clientId'
    | '/clients'
  id:
    | '__root__'
    | '/'
    | '/email'
    | '/queue'
    | '/reports'
    | '/sms'
    | '/viber'
    | '/voice'
    | '/whatsapp'
    | '/api/call-escalation-logs'
    | '/api/call-promise-logs'
    | '/api/channel-counters'
    | '/api/client-call-summary'
    | '/api/clients-list'
    | '/api/daily-run-logs'
    | '/api/escalations'
    | '/api/gmail-attachment'
    | '/api/gmail-thread-detail'
    | '/api/gmail-threads-list'
    | '/api/promise-history'
    | '/api/reminder-queue-list'
    | '/api/sms-conversations'
    | '/api/vapi-call-audio'
    | '/api/vapi-call-detail'
    | '/api/vapi-calls-list'
    | '/api/whatsapp-conversations'
    | '/clients/$clientId'
    | '/clients/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EmailRoute: typeof EmailRoute
  QueueRoute: typeof QueueRoute
  ReportsRoute: typeof ReportsRoute
  SmsRoute: typeof SmsRoute
  ViberRoute: typeof ViberRoute
  VoiceRoute: typeof VoiceRoute
  WhatsappRoute: typeof WhatsappRoute
  ApiCallEscalationLogsRoute: typeof ApiCallEscalationLogsRoute
  ApiCallPromiseLogsRoute: typeof ApiCallPromiseLogsRoute
  ApiChannelCountersRoute: typeof ApiChannelCountersRoute
  ApiClientCallSummaryRoute: typeof ApiClientCallSummaryRoute
  ApiClientsListRoute: typeof ApiClientsListRoute
  ApiDailyRunLogsRoute: typeof ApiDailyRunLogsRoute
  ApiEscalationsRoute: typeof ApiEscalationsRoute
  ApiGmailAttachmentRoute: typeof ApiGmailAttachmentRoute
  ApiGmailThreadDetailRoute: typeof ApiGmailThreadDetailRoute
  ApiGmailThreadsListRoute: typeof ApiGmailThreadsListRoute
  ApiPromiseHistoryRoute: typeof ApiPromiseHistoryRoute
  ApiReminderQueueListRoute: typeof ApiReminderQueueListRoute
  ApiSmsConversationsRoute: typeof ApiSmsConversationsRoute
  ApiVapiCallAudioRoute: typeof ApiVapiCallAudioRoute
  ApiVapiCallDetailRoute: typeof ApiVapiCallDetailRoute
  ApiVapiCallsListRoute: typeof ApiVapiCallsListRoute
  ApiWhatsappConversationsRoute: typeof ApiWhatsappConversationsRoute
  ClientsClientIdRoute: typeof ClientsClientIdRoute
  ClientsIndexRoute: typeof ClientsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email': {
      id: '/email'
      path: '/email'
      fullPath: '/email'
      preLoaderRoute: typeof EmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queue': {
      id: '/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof QueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sms': {
      id: '/sms'
      path: '/sms'
      fullPath: '/sms'
      preLoaderRoute: typeof SmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/viber': {
      id: '/viber'
      path: '/viber'
      fullPath: '/viber'
      preLoaderRoute: typeof ViberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voice': {
      id: '/voice'
      path: '/voice'
      fullPath: '/voice'
      preLoaderRoute: typeof VoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whatsapp': {
      id: '/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof WhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/call-escalation-logs': {
      id: '/api/call-escalation-logs'
      path: '/api/call-escalation-logs'
      fullPath: '/api/call-escalation-logs'
      preLoaderRoute: typeof ApiCallEscalationLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/call-promise-logs': {
      id: '/api/call-promise-logs'
      path: '/api/call-promise-logs'
      fullPath: '/api/call-promise-logs'
      preLoaderRoute: typeof ApiCallPromiseLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/channel-counters': {
      id: '/api/channel-counters'
      path: '/api/channel-counters'
      fullPath: '/api/channel-counters'
      preLoaderRoute: typeof ApiChannelCountersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/client-call-summary': {
      id: '/api/client-call-summary'
      path: '/api/client-call-summary'
      fullPath: '/api/client-call-summary'
      preLoaderRoute: typeof ApiClientCallSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/clients-list': {
      id: '/api/clients-list'
      path: '/api/clients-list'
      fullPath: '/api/clients-list'
      preLoaderRoute: typeof ApiClientsListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/daily-run-logs': {
      id: '/api/daily-run-logs'
      path: '/api/daily-run-logs'
      fullPath: '/api/daily-run-logs'
      preLoaderRoute: typeof ApiDailyRunLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/escalations': {
      id: '/api/escalations'
      path: '/api/escalations'
      fullPath: '/api/escalations'
      preLoaderRoute: typeof ApiEscalationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gmail-attachment': {
      id: '/api/gmail-attachment'
      path: '/api/gmail-attachment'
      fullPath: '/api/gmail-attachment'
      preLoaderRoute: typeof ApiGmailAttachmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gmail-thread-detail': {
      id: '/api/gmail-thread-detail'
      path: '/api/gmail-thread-detail'
      fullPath: '/api/gmail-thread-detail'
      preLoaderRoute: typeof ApiGmailThreadDetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gmail-threads-list': {
      id: '/api/gmail-threads-list'
      path: '/api/gmail-threads-list'
      fullPath: '/api/gmail-threads-list'
      preLoaderRoute: typeof ApiGmailThreadsListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/promise-history': {
      id: '/api/promise-history'
      path: '/api/promise-history'
      fullPath: '/api/promise-history'
      preLoaderRoute: typeof ApiPromiseHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reminder-queue-list': {
      id: '/api/reminder-queue-list'
      path: '/api/reminder-queue-list'
      fullPath: '/api/reminder-queue-list'
      preLoaderRoute: typeof ApiReminderQueueListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sms-conversations': {
      id: '/api/sms-conversations'
      path: '/api/sms-conversations'
      fullPath: '/api/sms-conversations'
      preLoaderRoute: typeof ApiSmsConversationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vapi-call-audio': {
      id: '/api/vapi-call-audio'
      path: '/api/vapi-call-audio'
      fullPath: '/api/vapi-call-audio'
      preLoaderRoute: typeof ApiVapiCallAudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vapi-call-detail': {
      id: '/api/vapi-call-detail'
      path: '/api/vapi-call-detail'
      fullPath: '/api/vapi-call-detail'
      preLoaderRoute: typeof ApiVapiCallDetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vapi-calls-list': {
      id: '/api/vapi-calls-list'
      path: '/api/vapi-calls-list'
      fullPath: '/api/vapi-calls-list'
      preLoaderRoute: typeof ApiVapiCallsListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/whatsapp-conversations': {
      id: '/api/whatsapp-conversations'
      path: '/api/whatsapp-conversations'
      fullPath: '/api/whatsapp-conversations'
      preLoaderRoute: typeof ApiWhatsappConversationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/': {
      id: '/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof ClientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/$clientId': {
      id: '/clients/$clientId'
      path: '/clients/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof ClientsClientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EmailRoute: EmailRoute,
  QueueRoute: QueueRoute,
  ReportsRoute: ReportsRoute,
  SmsRoute: SmsRoute,
  ViberRoute: ViberRoute,
  VoiceRoute: VoiceRoute,
  WhatsappRoute: WhatsappRoute,
  ApiCallEscalationLogsRoute: ApiCallEscalationLogsRoute,
  ApiCallPromiseLogsRoute: ApiCallPromiseLogsRoute,
  ApiChannelCountersRoute: ApiChannelCountersRoute,
  ApiClientCallSummaryRoute: ApiClientCallSummaryRoute,
  ApiClientsListRoute: ApiClientsListRoute,
  ApiDailyRunLogsRoute: ApiDailyRunLogsRoute,
  ApiEscalationsRoute: ApiEscalationsRoute,
  ApiGmailAttachmentRoute: ApiGmailAttachmentRoute,
  ApiGmailThreadDetailRoute: ApiGmailThreadDetailRoute,
  ApiGmailThreadsListRoute: ApiGmailThreadsListRoute,
  ApiPromiseHistoryRoute: ApiPromiseHistoryRoute,
  ApiReminderQueueListRoute: ApiReminderQueueListRoute,
  ApiSmsConversationsRoute: ApiSmsConversationsRoute,
  ApiVapiCallAudioRoute: ApiVapiCallAudioRoute,
  ApiVapiCallDetailRoute: ApiVapiCallDetailRoute,
  ApiVapiCallsListRoute: ApiVapiCallsListRoute,
  ApiWhatsappConversationsRoute: ApiWhatsappConversationsRoute,
  ClientsClientIdRoute: ClientsClientIdRoute,
  ClientsIndexRoute: ClientsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
